services:
  app:
    build:
      context: .
      target: dev
    container_name: part3_bai6_app_dev
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

  tests:
    build:
      context: .
      target: test
    container_name: part3_bai6_tests
    depends_on:
      - app
    volumes:
      - .:/app
      - /app/node_modules
    entrypoint: ["npm", "test", "--", "--watchAll"]
