services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - my_network
  db:
    image: mysql:8
    container_name: my_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge